### ISSUE TITLE
Code for evaluation.

### ISSUE THREAD

**Issue by guangkaixu** [dazinovic/neural-rgbd-surface-reconstruction#1]
Hi, thanks for your great contribution to reconstruction. Is there any code for evaluation of predicted point cloud, like "C-l1", "IoU", "NC" and "F-score" mentioned in the paper?

**Comment by dazinovic** [comment]
Hi guangkaixu,

The evaluation code was adapted from Convolutional Occupancy Networks:
https://github.com/autonomousvision/convolutional_occupancy_networks/blob/f15b97da2c5995598537c8f832e52e95c0b09236/src/eval.py

You might also be interested in RetrievalFuse since they build on the same code:
https://github.com/nihalsid/retrieval-fuse/blob/main/util/mesh_metrics.py

**Comment by guangkaixu** [comment]
Thanks for your reply. I performed evaluation code of RetrievalFuse following your second link on the same GT mesh, i.e. the same mesh for prediction and target, but I got 0.017 for L1 distance and 0.801 for normals_correctness, which should be 0 and 1 theoretically to my understanding. I think there may exist some mistakes for the evaluation code.
